export const countryCodesToCountry = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Aland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrein",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint-Barthélemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia",
    "BQ": "Caribbean Netherlands",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "Democratic Republic of the Congo (Congo-Kinshasa, former Zaire)",
    "CF": "Centrafrican Republic",
    "CG": "Republic of the Congo (Congo-Brazzaville)",
    "CH": "Switzerland",
    "CI": "Côte d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curaçao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands",
    "FM": "Micronesia (Federated States of)",
    "FO": "Faroe Islands",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "The Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong (SAR of China)",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comores",
    "KN": "Saint Kitts and Nevis",
    "KP": "North Korea",
    "KR": "South Korea",
    "KW": "Kuweit",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Laos",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova",
    "ME": "Montenegro",
    "MF": "Saint Martin (French part)",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Macedonia (Former Yugoslav Republic of)",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macao (SAR of China)",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "The Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestinian Territory",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Sénégal",
    "SO": "Somalia",
    "SR": "Suriname",
    "ST": "São Tomé and Príncipe",
    "SS": "South Sudan",
    "SV": "El Salvador",
    "SX": "Saint Martin (Dutch part)",
    "SY": "Syria",
    "SZ": "Swaziland",
    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern and Antarctic Lands",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "City of the Vatican",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "United States Virgin Islands",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna",
    "WS": "Samoa",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
  };

export const sweCityNames = {
    Athens:"Aten / Athen",
    Bucharest:"Buckarest",
    Baghdad:"Bagdad",
    Belgrade:"Belgrad",
    Cologne:"Köln",
    Florence:"Florens",
    Gothenburg:"Göteborg",
    Hamburger:"Hamburg",
    Havana:"Havanna",
    Helsinki:"Helsingfors",
    Cairo:"Kairo",
    Kyiv:"Kiev",
    ["Cape Town"]:"Kapstaden",
    Copenhagen:"Köpenhamn",
    Lebanon:"Libanon",
    Lisbon:"Lissabon",
    Milan:"Milano",
    Moscow:"Moskva",
    Munich:"Munchen",
    Napoli:"Neapel",
    ["New York City"]:"New York",
    Beijing:"Peking",
    Prague:"Prag",
    Rome:"Rom",
    Singapore:"Singapor",
    Venice:"Venedig",
    Warsaw:"Warszawa",
    Vienna:"Wien",
};

export const sweCountryNames = {
    Afghanistan:"Afganistan",
    Albania:"Albanien",
    Azerbaijan:"Azerbajdzjan",
    Algeria:"Algeriet",
    "Antigua and Barbuda":"",
    Australia:"Australien",
    "The Bahamas":"Bahamas",
    Barbados:"Barbados",
    Brazil:"Brasilien",
    "Bosnia and Herzegovina":"Bosnien och Hercegovina",
    Bangladesh:"Bangladesh",
    Belgium:"Belgien",
    Bulgaria:"Bulgarien",
    Denmark:"Danmark",
    Cyprus:"Cypern",
    Egypt:"Egypten",
    Estonia:"Estland",
    "Ivory Coast":"Elfenbenskusten",
    Ethiopia:"Etiopien",
    Philippines:"Filippinerna",
    France:"Frankrike",
    "The Gambia":"Gambia",
    Georgia:"Georgien",
    Greece:"Grekland",
    Iceland:"Island",
    India:"Indien",
    Indonesia:"Indonesien",
    Iraq:"Irak",
    Ireland:"Irland",
    Italy:"Italien",
    Kazakhstan:"Kazakstan",
    Cambodia:"Kambodja",
    Canada:"Kanada",
    Cameroon:"Kamerun",
    China:"Kina",
    Congo:"Kongo",
    Croatia:"Kroatien",
    Latvia:"Lettland",
    Lebanon:"Libanon",
    Libya:"Libyen",
    Lithuania:"Litauen",
    Luxembourg:"Luxemburg",
    Macedonia:"Makedonien",
    Madagascar:"Madagaskar",
    Maldives:"Maldiverna",
    Mexico:"Mexiko",
    Moldova:"Moldavien",
    Mongolia:"Mongoliet",
    Morocco:"Morocko",
    Mozambique:"Moçambique",
    Netherlands:"Nederländerna",
    "Northern Ireland":"Nordirland",
    Norway:"Norge",
    Paraguay:"Paraguay",
    Poland:"Polen",
    Romania:"Rumänien",
    Russia:"Ryssland",
    "Saudi Arabia":"Saudiarabien",
    Switzerland:"Schweiz",
    Serbia:"Serbien",
    Slovakia:"Slovakien",
    Slovenia:"Slovenien",
    Spain:"Spanien",
    "United Kingdom":"Storbritannien",
    Suriname:"Surinam",
    Sweden:"Sverige",
    "South Korea":"Sydkorea",
    Chad:"Tchad",
    Tunisia:"Tunisien",
    Turkey:"Turkiet",
    Germany:"Tyskland",
    Ukraine:"Ukraina",
    Hungary:"Ungern",
    "United States of America":"USA",
    Belarus:"Vitryssland",
    Austria:"Österrike",
    "Solomon Islands":"Salomonöarna",
    "Papua New Guinea":"Papua Nya Guinea",
    "South Africa":"Sydafrika",
    Greenland:"Grönland",
}